import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'si' | 'ta' | 'zh' | 'ja' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'Home',
    about: 'About',
    services: 'Services',
    pricing: 'Pricing',
    portfolio: 'Portfolio',
    blog: 'Blog',
    contact: 'Contact',
    getQuote: 'Get a Quote',
    heroTitle: 'We Build Professional Websites That Grow Your Business',
    heroSub: 'Modern, fast, and mobile-friendly websites designed to help businesses build trust, attract customers, and increase sales.',
    freeQuote: 'Get a Free Quote',
    viewPlans: 'View Our Plans',
    trustedBy: 'Trusted by 6+ businesses',
    ourExpertise: 'Our Expertise',
    compDigitalSolutions: 'Comprehensive Digital Solutions',
    compDigitalSolutionsSub: 'We provide everything you need to establish a powerful online presence and drive results.',
    learnMore: 'Learn More',
    whyChooseUs: 'Why Choose Us',
    successStoriesTitle: "We Don't Just Build Websites, We Build Success Stories",
    successStoriesSub: 'At Albecket Web Studio, we combine creative design with technical excellence to deliver websites that actually work for your business.',
    why1: 'Custom designs tailored to your specific business goals',
    why2: 'Mobile-first approach for seamless experience on all devices',
    why3: 'Optimized for speed and search engine performance',
    why4: 'Dedicated support and maintenance for peace of mind',
    why5: 'Transparent pricing with no hidden costs',
    discoverOurStory: 'Discover Our Story',
    ourPortfolio: 'Our Portfolio',
    featuredProjects: 'Featured Projects',
    viewAllProjects: 'View All Projects',
    testimonials: 'Testimonials',
    whatClientsSay: 'What Our Clients Say',
    readyToTransform: 'Ready to Transform Your Digital Presence?',
    readyToTransformSub: 'Join our growing list of successful businesses that trust Albecket Web Studio for their digital growth.',
    getStartedNow: 'Get Started Now',
    viewPricing: 'View Pricing',
    yearsExcellence: 'Years of Excellence',
    quickLinks: 'Quick Links',
    contactInfo: 'Contact Info',
    visitUs: 'Visit Us',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    allRightsReserved: 'All rights reserved.',
    footerDesc: 'Premium web design and digital services studio helping businesses build trust, attract customers, and increase sales with modern websites.',
    ourServices: 'Our Services',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    businessWebsites: 'Business Websites',
    ecommerceDev: 'Ecommerce Development',
    landingPages: 'Landing Pages',
    seoOptimization: 'SEO Optimization',
    websiteMaintenance: 'Website Maintenance',
    customDashboards: 'Custom Dashboards',
    aboutTitle: 'About Albecket Web Studio',
    aboutHeroTitle: 'We Are Creative Thinkers & Digital Builders',
    aboutHeroSub: 'Founded with a passion for excellence, Albecket Web Studio helps businesses bridge the gap between their vision and digital reality.',
    ourJourneyTitle: 'Our Journey to Excellence',
    ourJourneyP1: "What started as a small team of passionate designers has grown into a full-service digital agency. We've spent over a decade refining our process and mastering the latest technologies to ensure our clients always stay ahead of the curve.",
    ourJourneyP2: "We believe that a website is more than just code and pixels—it's a powerful tool for growth, a digital storefront, and a primary touchpoint for your customers. That's why we treat every project with the same level of care and precision as if it were our own.",
    projectsCompleted: 'Projects Completed',
    clientSatisfaction: 'Client Satisfaction',
    ourMission: 'Our Mission',
    ourMissionDesc: 'To empower businesses by creating high-performance digital solutions that drive growth, enhance brand value, and deliver exceptional user experiences.',
    ourVision: 'Our Vision',
    ourVisionDesc: 'To be the global leader in innovative web design, setting the standard for digital excellence and helping businesses thrive in an ever-evolving digital landscape.',
    valuesDriveUs: 'The Values That Drive Us',
    qualityFirst: 'Quality First',
    qualityFirstDesc: 'We never compromise on the quality of our work, ensuring every pixel is perfect.',
    clientCentric: 'Client Centric',
    clientCentricDesc: 'Your success is our success. We listen, understand, and deliver beyond expectations.',
    innovation: 'Innovation',
    innovationDesc: 'We constantly explore new technologies and trends to keep your business ahead.',
    servicesHeroTitle: 'Solutions Tailored to Your Business Growth',
    servicesHeroSub: 'From simple landing pages to complex ecommerce platforms, we deliver high-quality digital products that drive results.',
    noServices: 'No services listed yet.',
    needCustomSolution: 'Need a Custom Solution?',
    needCustomSolutionSub: 'If you have a unique project in mind, our team of experts is ready to help you bring it to life.',
    talkToExperts: 'Talk to Our Experts',
    pricingHeroTitle: 'Transparent Pricing for Every Business Stage',
    pricingHeroSub: 'Affordable web solutions for every business. Start your journey with us today. Choose a plan or order directly via WhatsApp for a custom quote.',
    mostPopular: 'Most Popular',
    whatsIncluded: "What's Included",
    delivery: 'Delivery',
    orderViaWhatsApp: 'Order via WhatsApp',
    noPricingPlans: 'No pricing plans listed yet. Check back soon!',
    faqTitle: 'Frequently Asked Questions',
    faqSub: 'Everything you need to know about our process and services.',
    faq1Q: 'How long does a typical project take?',
    faq1A: 'A Starter Plan project usually takes 3 days, while Business and Premium plans can take 1-3 weeks depending on complexity.',
    faq2Q: 'Do you offer payment plans?',
    faq2A: 'Yes, we typically require a 50% deposit to start, with the remaining balance due upon project completion.',
    faq3Q: 'Can I upgrade my plan later?',
    faq3A: 'Absolutely! You can start with a Starter Plan and upgrade as your business grows and needs more features.',
    faq4Q: 'What if I need custom features?',
    faq4A: 'Our Custom Pro Business Solution is designed exactly for that. We can build any feature your business requires.',
    perMonth: '/ month',
    perProject: '/ project',
    portfolioHeroTitle: 'Showcasing Our Best Digital Creations',
    portfolioHeroSub: 'Explore our diverse range of projects across various industries and technologies.',
    visitWebsite: 'Visit Website',
    noProjectsFound: 'No projects found in this category.',
    haveProjectInMind: 'Have a Project in Mind?',
    haveProjectInMindSub: "Let's work together to create something amazing for your business.",
    startYourProject: 'Start Your Project',
    catAll: 'All',
    catCorporate: 'Corporate',
    catEcommerce: 'Ecommerce',
    catLandingPage: 'Landing Page',
    catWebApp: 'Web App',
    contactHeroTitle: "Let's Start Your Next Digital Project",
    contactHeroSub: 'Have a question or ready to get started? Our team is here to help you build a powerful online presence.',
    getInTouch: 'Get in Touch',
    getInTouchSub: 'Fill out the form or use our contact details below. We typically respond within 24 hours on business days.',
    quickChatWhatsApp: 'Quick Chat on WhatsApp',
    quickChatWhatsAppSub: 'Prefer a faster way to communicate? Chat with us directly on WhatsApp for immediate assistance.',
    startChattingNow: 'Start Chatting Now',
    messageSent: 'Message Sent!',
    messageSentSub: 'Thank you for reaching out. Our team will get back to you within 24 hours.',
    sendAnotherMessage: 'Send another message',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number (Optional)',
    yourMessage: 'Your Message',
    sending: 'Sending...',
    sendMessage: 'Send Message',
    commonQuestions: 'Common Questions',
    blogHeroTitle: 'Latest News & Digital Marketing Tips',
    blogHeroSub: 'Blog & Insights',
    searchArticles: 'Search articles...',
    readMore: 'Read More',
    noArticlesFound: 'No articles found matching your search.',
    loadingBlog: 'Loading Blog...',
    backToBlog: 'Back to Blog',
    sharePost: 'Share this post',
    aboutAuthor: 'About the Author',
    needAWebsite: 'Need a Professional Website?',
    getStarted: 'Get Started',
  },
  si: {
    home: 'මුල් පිටුව',
    about: 'අප ගැන',
    services: 'සේවාවන්',
    pricing: 'මිල ගණන්',
    portfolio: 'නිර්මාණ එකතුව',
    blog: 'බ්ලොග්',
    contact: 'සම්බන්ධ වන්න',
    getQuote: 'මිල ගණන් ලබා ගන්න',
    heroTitle: 'ඔබේ ව්‍යාපාරය දියුණු කරන වෘත්තීය වෙබ් අඩවි අපි නිර්මාණය කරමු',
    heroSub: 'ව්‍යාපාර කෙරෙහි විශ්වාසය තැබීමට, පාරිභෝගිකයින් ආකර්ෂණය කර ගැනීමට සහ විකුණුම් වැඩි කිරීමට උපකාරී වන නවීන, වේගවත් සහ ජංගම දුරකථන සඳහා හිතකාමී වෙබ් අඩවි.',
    freeQuote: 'නොමිලේ මිල ගණන් ලබා ගන්න',
    viewPlans: 'අපගේ සැලසුම් බලන්න',
    trustedBy: 'ව්‍යාපාර 6+ ක විශ්වාසය දිනූ',
    ourExpertise: 'අපගේ විශේෂඥතාව',
    compDigitalSolutions: 'සම්පූර්ණ ඩිජිටල් විසඳුම්',
    compDigitalSolutionsSub: 'ප්‍රබල ඔන්ලයින් පැවැත්මක් ඇති කිරීමට සහ ප්‍රතිඵල ලබා ගැනීමට අවශ්‍ය සියල්ල අපි ලබා දෙන්නෙමු.',
    learnMore: 'වැඩි විස්තර',
    whyChooseUs: 'අපව තෝරා ගන්නේ ඇයි',
    successStoriesTitle: 'අපි වෙබ් අඩවි පමණක් නොව සාර්ථක කතාන්දර නිර්මාණය කරමු',
    successStoriesSub: 'Albecket Web Studio හිදී, අපි ඔබේ ව්‍යාපාරය සඳහා සැබවින්ම ක්‍රියා කරන වෙබ් අඩවි ලබා දීම සඳහා නිර්මාණාත්මක සැලසුම් තාක්ෂණික විශිෂ්ටත්වය සමඟ ඒකාබද්ධ කරමු.',
    why1: 'ඔබේ ව්‍යාපාරික ඉලක්ක වලට ගැලපෙන පරිදි සකස් කළ නිර්මාණ',
    why2: 'සියලුම උපාංග වල හොඳින් ක්‍රියා කරන Mobile-first ප්‍රවේශය',
    why3: 'වේගය සහ සෙවුම් යන්ත්‍ර (SEO) සඳහා ප්‍රශස්ත කර ඇත',
    why4: 'විශ්වාසදායක සහය සහ නඩත්තුව',
    why5: 'සැඟවුණු පිරිවැයකින් තොර විනිවිද පෙනෙන මිල ගණන්',
    discoverOurStory: 'අපගේ කතාව දැනගන්න',
    ourPortfolio: 'අපගේ නිර්මාණ',
    featuredProjects: 'විශේෂිත ව්‍යාපෘති',
    viewAllProjects: 'සියලුම ව්‍යාපෘති බලන්න',
    testimonials: 'පාරිභෝගික අදහස්',
    whatClientsSay: 'අපගේ ගනුදෙනුකරුවන් පවසන දේ',
    readyToTransform: 'ඔබේ ඩිජිටල් පැවැත්ම වෙනස් කිරීමට සූදානම්ද?',
    readyToTransformSub: 'ඔවුන්ගේ ඩිජිටල් වර්ධනය සඳහා Albecket Web Studio විශ්වාස කරන සාර්ථක ව්‍යාපාර ලැයිස්තුවට එක්වන්න.',
    getStartedNow: 'දැන්ම ආරම්භ කරන්න',
    viewPricing: 'මිල ගණන් බලන්න',
    yearsExcellence: 'වසර 10 ක විශිෂ්ටත්වය',
    quickLinks: 'ප්‍රධාන සබැඳි',
    contactInfo: 'සම්බන්ධතා තොරතුරු',
    visitUs: 'අපව හමුවන්න',
    callUs: 'අපට අමතන්න',
    emailUs: 'ඊමේල් කරන්න',
    allRightsReserved: 'සියලුම හිමිකම් ඇවිරිණි.',
    footerDesc: 'ව්‍යාපාර කෙරෙහි විශ්වාසය තැබීමට, පාරිභෝගිකයින් ආකර්ෂණය කර ගැනීමට සහ නවීන වෙබ් අඩවි සමඟ විකුණුම් වැඩි කිරීමට උපකාරී වන වෘත්තීය වෙබ් නිර්මාණ සහ ඩිජිටල් සේවා ආයතනයකි.',
    ourServices: 'අපගේ සේවාවන්',
    privacyPolicy: 'පෞද්ගලිකත්ව ප්‍රතිපත්තිය',
    termsOfService: 'සේවා කොන්දේසි',
    businessWebsites: 'ව්‍යාපාරික වෙබ් අඩවි',
    ecommerceDev: 'ඊ-කොමර්ස් සංවර්ධනය',
    landingPages: 'Landing Pages',
    seoOptimization: 'SEO ප්‍රශස්තකරණය',
    websiteMaintenance: 'වෙබ් අඩවි නඩත්තුව',
    customDashboards: 'Custom Dashboards',
    aboutTitle: 'Albecket Web Studio ගැන',
    aboutHeroTitle: 'අපි නිර්මාණශීලී චින්තකයින් සහ ඩිජිටල් නිර්මාණකරුවන් වෙමු',
    aboutHeroSub: 'විශිෂ්ටත්වය සඳහා වූ කැපවීමෙන් ආරම්භ කරන ලද Albecket Web Studio ව්‍යාපාරවල දැක්ම සහ ඩිජිටල් යථාර්ථය අතර පරතරය පියවීමට උපකාරී වේ.',
    ourJourneyTitle: 'විශිෂ්ටත්වය කරා අපගේ ගමන',
    ourJourneyP1: 'කුඩා නිර්මාණකරුවන් කණ්ඩායමකින් ආරම්භ වූ අප දැන් පූර්ණ ඩිජිටල් ආයතනයක් දක්වා වර්ධනය වී ඇත. අපගේ ගනුදෙනුකරුවන් සැමවිටම ඉදිරියෙන් සිටින බව සහතික කිරීම සඳහා අපි දශකයකට වැඩි කාලයක් අපගේ ක්‍රියාවලිය පිරිපහදු කරමින් නවතම තාක්ෂණයන් ප්‍රගුණ කර ඇත්තෙමු.',
    ourJourneyP2: 'වෙබ් අඩවියක් යනු කේත සහ පික්සෙල් වලට වඩා වැඩි යමක් බව අපි විශ්වාස කරමු - එය වර්ධනය සඳහා ප්‍රබල මෙවලමක්, ඩිජිටල් වෙළඳසැලක් සහ ඔබේ ගනුදෙනුකරුවන් සඳහා ප්‍රධාන ස්පර්ශක ලක්ෂ්‍යයකි. ඒ නිසාම අපි සෑම ව්‍යාපෘතියක්ම අපගේම ව්‍යාපෘතියක් ලෙස සලකා ඉතාම සැලකිල්ලෙන් සහ නිරවද්‍යතාවයෙන් යුතුව සිදු කරන්නෙමු.',
    projectsCompleted: 'නිම කරන ලද ව්‍යාපෘති',
    clientSatisfaction: 'පාරිභෝගික තෘප්තිය',
    ourMission: 'අපගේ මෙහෙවර',
    ourMissionDesc: 'වර්ධනය ප්‍රවර්ධනය කරන, සන්නාම වටිනාකම ඉහළ නංවන සහ සුවිශේෂී පරිශීලක අත්දැකීම් ලබා දෙන ඉහළ කාර්ය සාධනයක් සහිත ඩිජිටල් විසඳුම් නිර්මාණය කිරීම මගින් ව්‍යාපාර බල ගැන්වීම.',
    ourVision: 'අපගේ දැක්ම',
    ourVisionDesc: 'නව්‍ය වෙබ් නිර්මාණකරණයේ ගෝලීය ප්‍රමුඛයා වීම, ඩිජිටල් විශිෂ්ටත්වය සඳහා ප්‍රමිතිය සැකසීම සහ නිරන්තරයෙන් විකාශනය වන ඩිජිටල් ලෝකය තුළ ව්‍යාපාරවලට දියුණු වීමට උපකාර කිරීම.',
    valuesDriveUs: 'අපව මෙහෙයවන වටිනාකම්',
    qualityFirst: 'ගුණාත්මකභාවය ප්‍රමුඛයි',
    qualityFirstDesc: 'අපගේ කාර්යයේ ගුණාත්මකභාවය පිළිබඳව අපි කිසිවිටෙකත් සම්මුතියක් ඇති කර නොගනිමු, සෑම පික්සලයක්ම පරිපූර්ණ බව සහතික කරමු.',
    clientCentric: 'පාරිභෝගික කේන්ද්‍රීය',
    clientCentricDesc: 'ඔබේ සාර්ථකත්වය අපේ සාර්ථකත්වයයි. අපි සවන් දෙන්නෙමු, තේරුම් ගන්නෙමු, සහ බලාපොරොත්තු වූවාට වඩා වැඩි යමක් ලබා දෙන්නෙමු.',
    innovation: 'නවෝත්පාදනය',
    innovationDesc: 'ඔබේ ව්‍යාපාරය ඉදිරියෙන් තැබීම සඳහා අපි නිරන්තරයෙන් නව තාක්ෂණයන් සහ ප්‍රවණතා ගවේෂණය කරන්නෙමු.',
    servicesHeroTitle: 'ඔබේ ව්‍යාපාරයේ වර්ධනයට ගැලපෙන විසඳුම්',
    servicesHeroSub: 'සරල Landing Pages සිට සංකීර්ණ ඊ-කොමර්ස් වේදිකා දක්වා, අපි ප්‍රතිඵල ලබා දෙන උසස් තත්ත්වයේ ඩිජිටල් නිෂ්පාදන ලබා දෙන්නෙමු.',
    noServices: 'තවමත් සේවාවන් ලැයිස්තුගත කර නොමැත.',
    needCustomSolution: 'ඔබට විශේෂිත විසඳුමක් අවශ්‍යද?',
    needCustomSolutionSub: 'ඔබේ සිතේ සුවිශේෂී ව්‍යාපෘතියක් තිබේ නම්, එය සාර්ථක කර ගැනීමට අපගේ විශේෂඥ කණ්ඩායම සූදානම්.',
    talkToExperts: 'අපගේ විශේෂඥයන් සමඟ කතා කරන්න',
    pricingHeroTitle: 'සෑම ව්‍යාපාරික මට්ටමකටම ගැලපෙන විනිවිද පෙනෙන මිල ගණන්',
    pricingHeroSub: 'සෑම ව්‍යාපාරයක් සඳහාම දැරිය හැකි වෙබ් විසඳුම්. අදම අප සමඟ ඔබේ ගමන ආරම්භ කරන්න. සැලසුමක් තෝරන්න හෝ විශේෂිත මිල ගණන් සඳහා WhatsApp හරහා අප හා සම්බන්ධ වන්න.',
    mostPopular: 'වඩාත් ජනප්‍රිය',
    whatsIncluded: 'ඇතුළත් දෑ',
    delivery: 'ලබා දීම',
    orderViaWhatsApp: 'WhatsApp හරහා ඇණවුම් කරන්න',
    noPricingPlans: 'තවමත් මිල ගණන් ලැයිස්තුගත කර නොමැත. ඉක්මනින් නැවත පරීක්ෂා කරන්න!',
    faqTitle: 'නිතර අසන ප්‍රශ්න',
    faqSub: 'අපගේ ක්‍රියාවලිය සහ සේවාවන් ගැන ඔබ දැනගත යුතු සියල්ල.',
    faq1Q: 'සාමාන්‍ය ව්‍යාපෘතියක් සඳහා කොපමණ කාලයක් ගතවේද?',
    faq1A: 'Starter Plan ව්‍යාපෘතියක් සඳහා සාමාන්‍යයෙන් දින 3ක් ගතවන අතර Business සහ Premium සැලසුම් සඳහා සංකීර්ණත්වය අනුව සති 1-3ක් ගත විය හැක.',
    faq2Q: 'ඔබ ගෙවීමේ සැලසුම් ලබා දෙනවාද?',
    faq2A: 'ඔව්, අපි සාමාන්‍යයෙන් ආරම්භ කිරීමට 50% ක තැන්පතුවක් අවශ්‍ය වන අතර ඉතිරි මුදල ව්‍යාපෘතිය අවසානයේ ගෙවිය යුතුය.',
    faq3Q: 'මට පසුව මගේ සැලසුම උසස් (upgrade) කළ හැකිද?',
    faq3A: 'අනිවාර්යයෙන්ම! ඔබට Starter Plan එකකින් ආරම්භ කර ඔබේ ව්‍යාපාරය වර්ධනය වන විට අවශ්‍යතාවය අනුව upgrade කළ හැක.',
    faq4Q: 'මට විශේෂිත අංග (custom features) අවශ්‍ය නම්?',
    faq4A: 'අපගේ Custom Pro Business Solution නිර්මාණය කර ඇත්තේ ඒ සඳහාමය. ඔබේ ව්‍යාපාරයට අවශ්‍ය ඕනෑම අංගයක් අපට නිර්මාණය කළ හැක.',
    perMonth: '/ මසකට',
    perProject: '/ ව්‍යාපෘතියකට',
    portfolioHeroTitle: 'අපගේ හොඳම ඩිජිටල් නිර්මාණ',
    portfolioHeroSub: 'විවිධ කර්මාන්ත සහ තාක්ෂණයන් හරහා අපගේ විවිධ ව්‍යාපෘති ගවේෂණය කරන්න.',
    visitWebsite: 'වෙබ් අඩවියට පිවිසෙන්න',
    noProjectsFound: 'මෙම ගණය යටතේ කිසිදු ව්‍යාපෘතියක් හමු නොවීය.',
    haveProjectInMind: 'ඔබේ සිතේ ව්‍යාපෘතියක් තිබේද?',
    haveProjectInMindSub: 'ඔබේ ව්‍යාපාරය සඳහා පුදුමාකාර යමක් නිර්මාණය කිරීමට අපි එක්ව වැඩ කරමු.',
    startYourProject: 'ඔබේ ව්‍යාපෘතිය ආරම්භ කරන්න',
    catAll: 'සියල්ල',
    catCorporate: 'ව්‍යාපාරික',
    catEcommerce: 'ඊ-කොමර්ස්',
    catLandingPage: 'Landing Page',
    catWebApp: 'Web App',
    contactHeroTitle: 'අපි ඔබේ මීළඟ ඩිජිටල් ව්‍යාපෘතිය ආරම්භ කරමු',
    contactHeroSub: 'ඔබට ප්‍රශ්නයක් තිබේද නැතිනම් ආරම්භ කිරීමට සූදානම්ද? ප්‍රබල ඔන්ලයින් පැවැත්මක් ගොඩනැගීමට අපගේ කණ්ඩායම ඔබට උදවු කිරීමට සූදානම්.',
    getInTouch: 'සම්බන්ධ වන්න',
    getInTouchSub: 'පහත පෝරමය පුරවන්න හෝ අපගේ සම්බන්ධතා තොරතුරු භාවිතා කරන්න. අපි සාමාන්‍යයෙන් වැඩ කරන දිනවල පැය 24ක් ඇතුළත ප්‍රතිචාර දක්වන්නෙමු.',
    quickChatWhatsApp: 'WhatsApp හරහා ඉක්මනින් සම්බන්ධ වන්න',
    quickChatWhatsAppSub: 'වේගවත් සන්නිවේදන ක්‍රමයකට කැමතිද? ක්ෂණික සහාය සඳහා WhatsApp හරහා සෘජුවම අප සමඟ කතා කරන්න.',
    startChattingNow: 'දැන්ම කතා කරන්න',
    messageSent: 'පණිවිඩය යවන ලදී!',
    messageSentSub: 'අප හා සම්බන්ධ වීම ගැන ස්තූතියි. අපගේ කණ්ඩායම පැය 24ක් ඇතුළත ඔබව සම්බන්ධ කර ගනු ඇත.',
    sendAnotherMessage: 'තවත් පණිවිඩයක් යවන්න',
    fullName: 'සම්පූර්ණ නම',
    emailAddress: 'ඊමේල් ලිපිනය',
    phoneNumber: 'දුරකථන අංකය (අත්‍යවශ්‍ය නොවේ)',
    yourMessage: 'ඔබේ පණිවිඩය',
    sending: 'යවමින්...',
    sendMessage: 'පණිවිඩය යවන්න',
    commonQuestions: 'පොදු ප්‍රශ්න',
    blogHeroTitle: 'නවතම පුවත් සහ ඩිජිටල් අලෙවිකරණ උපදෙස්',
    blogHeroSub: 'බ්ලොග් සහ තොරතුරු',
    searchArticles: 'ලිපි සොයන්න...',
    readMore: 'වැඩි විස්තර',
    noArticlesFound: 'ඔබේ සෙවුමට ගැලපෙන ලිපි කිසිවක් හමු නොවීය.',
    loadingBlog: 'බ්ලොග් අඩවිය පූරණය වෙමින් පවතී...',
    backToBlog: 'බ්ලොග් අඩවියට ආපසු',
    sharePost: 'මෙම ලිපිය බෙදාගන්න',
    aboutAuthor: 'කර්තෘ ගැන',
    needAWebsite: 'වෘත්තීය වෙබ් අඩවියක් අවශ්‍යද?',
    getStarted: 'ආරම්භ කරන්න',
  },
  ta: {
    home: 'முகப்பு',
    about: 'பற்றி',
    services: 'சேவைகள்',
    pricing: 'விலை',
    portfolio: 'போர்ட்ஃபோலியோ',
    blog: 'வலைப்பதிவு',
    contact: 'தொடர்பு',
    getQuote: 'மேற்கோள் பெறுக',
    heroTitle: 'உங்கள் வணிகத்தை வளர்க்கும் தொழில்முறை வலைத்தளங்களை நாங்கள் உருவாக்குகிறோம்',
    heroSub: 'வணிகங்கள் நம்பிக்கையை வளர்க்கவும், வாடிக்கையாளர்களை ஈர்க்கவும் மற்றும் விற்பனையை அதிகரிக்கவும் உதவும் நவீன, வேகமான மற்றும் மொபைல் நட்பு வலைத்தளங்கள்.',
    freeQuote: 'இலவச மேற்கோள் பெறுக',
    viewPlans: 'எங்கள் திட்டங்களைப் பார்க்கவும்',
  },
  zh: {
    home: '首页',
    about: '关于',
    services: '服务',
    pricing: '定价',
    portfolio: '作品集',
    blog: '博客',
    contact: '联系我们',
    getQuote: '获取报价',
    heroTitle: '我们构建助力业务增长的专业网站',
    heroSub: '现代、快速且适合移动设备的网站，旨在帮助企业建立信任、吸引客户并增加销售额。',
    freeQuote: '获取免费报价',
    viewPlans: '查看我们的计划',
  },
  ja: {
    home: 'ホーム',
    about: '会社概要',
    services: 'サービス',
    pricing: '料金',
    portfolio: '実績',
    blog: 'ブログ',
    contact: 'お問い合わせ',
    getQuote: '見積もり依頼',
    heroTitle: 'ビジネスを成長させるプロフェッショナルなウェブサイトを構築します',
    heroSub: '信頼を築き、顧客を惹きつけ、売上を向上させるために設計された、モダンで高速、モバイルフレンドリーなウェブサイト。',
    freeQuote: '無料見積もり',
    viewPlans: 'プランを見る',
  },
  ru: {
    home: 'Главная',
    about: 'О нас',
    services: 'Услуги',
    pricing: 'Цены',
    portfolio: 'Портфолио',
    blog: 'Блог',
    contact: 'Контакт',
    getQuote: 'Получить расчет',
    heroTitle: 'Мы создаем профессиональные сайты, которые развивают ваш бизнес',
    heroSub: 'Современные, быстрые и адаптивные сайты, созданные для того, чтобы помочь бизнесу завоевать доверие, привлечь клиентов и увеличить продажи.',
    freeQuote: 'Бесплатный расчет',
    viewPlans: 'Посмотреть тарифы',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
